stages:
  - package
  - s3-package

# GitCode 禁用缓存（GitCode 未启用缓存），节省时间
#cache:
#  paths:
#    - .m2/repository

#
# package
package:
  variables:
    MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  stage: package
  image: maven:3.6.3-openjdk-17
  script:
    - GPG_FILE=/builds/xuxiaowei-cloud/xuxiaowei-cloud-next.tmp/xuxiaowei_0x97A36125_SECRET
    - echo $GPG_FILE
    - gpg --import $GPG_FILE
    - SETTINGS_FILE=/usr/share/maven/conf/settings.xml
    - echo $SETTINGS_FILE
    - sed -i "s#</servers>#<server><id>ossrh</id><username>$ossrh_user</username><password>$ossrh_pass</password></server>&#" $SETTINGS_FILE
    - sed -i "s#</mirrors>#<mirror><id>mirror</id><mirrorOf>central,jcenter,!rdc-releases,!rdc-snapshots</mirrorOf><name>mirror</name><url>https://maven.aliyun.com/nexus/content/groups/public</url></mirror>&#" $SETTINGS_FILE
    - git --version
    - echo 常量网址：https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - echo 当前分支：$CI_COMMIT_BRANCH
    - echo 主分支：$CI_DEFAULT_BRANCH
    - echo 项目路径：$CI_PROJECT_DIR
    - mvn clean -e -U package source:jar javadoc:jar install -Pgpg -DskipTests && PACKAGE_FLAG=1
    - if [ "$PACKAGE_FLAG" == "1" ]; then echo '打包完成'; else echo '打包失败' && xxxx; fi
  artifacts:
    name: package
    paths:
      - target/*.jar
      - target/*.asc
      - target/*.pom
      - "*/target/*.jar"
      - "*/target/*.asc"
      - "*/target/*.pom"
      - "*/*/target/*.jar"
      - "*/*/target/*.asc"
      - "*/*/target/*.pom"
  only:
    - main

#
# s3 打包
s3-package:
  stage: s3-package
  image: maven:3.6.3-openjdk-17
  script:
    - GPG_FILE=/builds/xuxiaowei-cloud/xuxiaowei-cloud-next.tmp/xuxiaowei_0x97A36125_SECRET
    - echo $GPG_FILE
    - gpg --import $GPG_FILE
    - SETTINGS_FILE=/usr/share/maven/conf/settings.xml
    - echo $SETTINGS_FILE
    - sed -i "s#</servers>#<server><id>ossrh</id><username>$ossrh_user</username><password>$ossrh_pass</password></server>&#" $SETTINGS_FILE
    - sed -i "s#</mirrors>#<mirror><id>mirror</id><mirrorOf>central,jcenter,!rdc-releases,!rdc-snapshots</mirrorOf><name>mirror</name><url>https://maven.aliyun.com/nexus/content/groups/public</url></mirror>&#" $SETTINGS_FILE
    - git --version
    - echo 常量网址：https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - echo 当前分支：$CI_COMMIT_BRANCH
    - echo 主分支：$CI_DEFAULT_BRANCH
    - echo 项目路径：$CI_PROJECT_DIR
    - mvn clean -e -U package source:jar javadoc:jar install -Pgpg -DskipTests && PACKAGE_FLAG=1
    - if [ "$PACKAGE_FLAG" == "1" ]; then echo '打包完成'; else echo '打包失败' && xxxx; fi
  artifacts:
    paths:
      - target/*.jar
      - target/*.asc
      - target/*.pom
      - "*/target/*.jar"
      - "*/target/*.asc"
      - "*/target/*.pom"
      - "*/*/target/*.jar"
      - "*/*/target/*.asc"
      - "*/*/target/*.pom"
      - ui/dist
  only:
    - s3

# 嵌入
include:
  # 对象储存
  # 已禁用，有需要时才开放此内容
  # - /upload.yml
  # 服务部署
  - /service.yml
