version: '1.0'
name: package
displayName: 打包
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - main
        - xuxiaowei
  pr:
    branches:
      precise:
        - main
stages:
  - name: package
    displayName: 打包
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven 构建
        jdkVersion: '17'
        mavenVersion: 3.6.3
        commands:
          - mvn package source:jar javadoc:jar install -DskipTests
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - admin-server/target/admin-server-0.0.1-SNAPSHOT.jar
              - gateway/target/gateway-0.0.1-SNAPSHOT.jar
              - passport/target/passport-0.0.1-SNAPSHOT.jar
              - passport-ui/target/passport-ui-0.0.1-SNAPSHOT.jar
        settings: []
        caches:
          - ~/.m2
          - passport-ui/node/
          - passport-ui/node_modules/
          - ui/node/
          - ui/node_modules/
        strategy:
          retry: '0'
strategy:
  blocking: false
permissions:
  - role: admin
    members: []
